language: node_js
node_js:
  - 12
script:
  - yarn run webpack:build
  - yarn test
deploy:
  provider: pages
  local_dir: './dist'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
